package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DatosArchivo generated by hbm2java
 */
@Entity
@Table(name = "DatosArchivo", catalog = "sgvdb")
public class DatosArchivo implements java.io.Serializable {

	private Integer idDatosArchivo;
	private String lugarAdquisicion;
	private int deadband1;
	private Integer deadband2;
	private Integer deadband3;
	private String sobreescritura;
	private int altura1;
	private Integer altura2;
	private Integer altura3;
	private int intervalo;
	private Integer cantidadPaquetes;

	public DatosArchivo() {
	}

	public DatosArchivo(String lugarAdquisicion, int deadband1,
			String sobreescritura, int altura1, int intervalo) {
		this.lugarAdquisicion = lugarAdquisicion;
		this.deadband1 = deadband1;
		this.sobreescritura = sobreescritura;
		this.altura1 = altura1;
		this.intervalo = intervalo;
	}

	public DatosArchivo(String lugarAdquisicion, int deadband1,
			Integer deadband2, Integer deadband3, String sobreescritura,
			int altura1, Integer altura2, Integer altura3, int intervalo,
			Integer cantidadPaquetes) {
		this.lugarAdquisicion = lugarAdquisicion;
		this.deadband1 = deadband1;
		this.deadband2 = deadband2;
		this.deadband3 = deadband3;
		this.sobreescritura = sobreescritura;
		this.altura1 = altura1;
		this.altura2 = altura2;
		this.altura3 = altura3;
		this.intervalo = intervalo;
		this.cantidadPaquetes = cantidadPaquetes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDatosArchivo", unique = true, nullable = false)
	public Integer getIdDatosArchivo() {
		return this.idDatosArchivo;
	}

	public void setIdDatosArchivo(Integer idDatosArchivo) {
		this.idDatosArchivo = idDatosArchivo;
	}

	@Column(name = "lugarAdquisicion", nullable = false, length = 45)
	public String getLugarAdquisicion() {
		return this.lugarAdquisicion;
	}

	public void setLugarAdquisicion(String lugarAdquisicion) {
		this.lugarAdquisicion = lugarAdquisicion;
	}

	@Column(name = "deadband1", nullable = false)
	public int getDeadband1() {
		return this.deadband1;
	}

	public void setDeadband1(int deadband1) {
		this.deadband1 = deadband1;
	}

	@Column(name = "deadband2")
	public Integer getDeadband2() {
		return this.deadband2;
	}

	public void setDeadband2(Integer deadband2) {
		this.deadband2 = deadband2;
	}

	@Column(name = "deadband3")
	public Integer getDeadband3() {
		return this.deadband3;
	}

	public void setDeadband3(Integer deadband3) {
		this.deadband3 = deadband3;
	}

	@Column(name = "sobreescritura", nullable = false, length = 2)
	public String getSobreescritura() {
		return this.sobreescritura;
	}

	public void setSobreescritura(String sobreescritura) {
		this.sobreescritura = sobreescritura;
	}

	@Column(name = "altura1", nullable = false)
	public int getAltura1() {
		return this.altura1;
	}

	public void setAltura1(int altura1) {
		this.altura1 = altura1;
	}

	@Column(name = "altura2")
	public Integer getAltura2() {
		return this.altura2;
	}

	public void setAltura2(Integer altura2) {
		this.altura2 = altura2;
	}

	@Column(name = "altura3")
	public Integer getAltura3() {
		return this.altura3;
	}

	public void setAltura3(Integer altura3) {
		this.altura3 = altura3;
	}

	@Column(name = "intervalo", nullable = false)
	public int getIntervalo() {
		return this.intervalo;
	}

	public void setIntervalo(int intervalo) {
		this.intervalo = intervalo;
	}

	@Column(name = "cantidadPaquetes")
	public Integer getCantidadPaquetes() {
		return this.cantidadPaquetes;
	}

	public void setCantidadPaquetes(Integer cantidadPaquetes) {
		this.cantidadPaquetes = cantidadPaquetes;
	}

}
