package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatosTodos generated by hbm2java
 */
@Entity
@Table(name = "DatosTodos", catalog = "sgvdb")
public class DatosTodos implements java.io.Serializable {

	private Integer idDatosTodos;
	private Date fecha;
	private Date hora;
	private BigDecimal tempProm;
	private Integer humedad;
	private Integer presion;
	private BigDecimal tempMax;
	private BigDecimal tempMin;
	private BigDecimal velPromAlt1;
	private int dirPromAlt1;
	private BigDecimal tempPromAlt1;
	private BigDecimal desvioAlt1;
	private BigDecimal velMaxAlt1;
	private int dirMaxAlt1;
	private BigDecimal tempMaxAlt1;
	private BigDecimal velMinAlt1;
	private int dirMinAlt1;
	private BigDecimal tempMinAlt1;
	private BigDecimal velPromAlt2;
	private Integer dirPromAlt2;
	private BigDecimal tempPromAlt2;
	private BigDecimal desvioAlt2;
	private BigDecimal velMaxAlt2;
	private Integer dirMaxAlt2;
	private BigDecimal tempMaxAlt2;
	private BigDecimal velMinAlt2;
	private Integer dirMinAlt2;
	private BigDecimal tempMinAlt2;
	private BigDecimal velPromAlt3;
	private Integer dirPromAlt3;
	private BigDecimal tempPromAlt3;
	private BigDecimal desvioAlt3;
	private BigDecimal velMaxAlt3;
	private Integer dirMaxAlt3;
	private BigDecimal tempMaxAlt3;
	private BigDecimal velMinAlt3;
	private Integer dirMinAlt3;
	private BigDecimal tempMinAlt3;

	public DatosTodos() {
	}

	public DatosTodos(Date fecha, Date hora, BigDecimal velPromAlt1,
			int dirPromAlt1, BigDecimal tempPromAlt1, BigDecimal desvioAlt1,
			BigDecimal velMaxAlt1, int dirMaxAlt1, BigDecimal tempMaxAlt1,
			BigDecimal velMinAlt1, int dirMinAlt1, BigDecimal tempMinAlt1) {
		this.fecha = fecha;
		this.hora = hora;
		this.velPromAlt1 = velPromAlt1;
		this.dirPromAlt1 = dirPromAlt1;
		this.tempPromAlt1 = tempPromAlt1;
		this.desvioAlt1 = desvioAlt1;
		this.velMaxAlt1 = velMaxAlt1;
		this.dirMaxAlt1 = dirMaxAlt1;
		this.tempMaxAlt1 = tempMaxAlt1;
		this.velMinAlt1 = velMinAlt1;
		this.dirMinAlt1 = dirMinAlt1;
		this.tempMinAlt1 = tempMinAlt1;
	}

	public DatosTodos(Date fecha, Date hora, BigDecimal tempProm,
			Integer humedad, Integer presion, BigDecimal tempMax,
			BigDecimal tempMin, BigDecimal velPromAlt1, int dirPromAlt1,
			BigDecimal tempPromAlt1, BigDecimal desvioAlt1,
			BigDecimal velMaxAlt1, int dirMaxAlt1, BigDecimal tempMaxAlt1,
			BigDecimal velMinAlt1, int dirMinAlt1, BigDecimal tempMinAlt1,
			BigDecimal velPromAlt2, Integer dirPromAlt2,
			BigDecimal tempPromAlt2, BigDecimal desvioAlt2,
			BigDecimal velMaxAlt2, Integer dirMaxAlt2, BigDecimal tempMaxAlt2,
			BigDecimal velMinAlt2, Integer dirMinAlt2, BigDecimal tempMinAlt2,
			BigDecimal velPromAlt3, Integer dirPromAlt3,
			BigDecimal tempPromAlt3, BigDecimal desvioAlt3,
			BigDecimal velMaxAlt3, Integer dirMaxAlt3, BigDecimal tempMaxAlt3,
			BigDecimal velMinAlt3, Integer dirMinAlt3, BigDecimal tempMinAlt3) {
		this.fecha = fecha;
		this.hora = hora;
		this.tempProm = tempProm;
		this.humedad = humedad;
		this.presion = presion;
		this.tempMax = tempMax;
		this.tempMin = tempMin;
		this.velPromAlt1 = velPromAlt1;
		this.dirPromAlt1 = dirPromAlt1;
		this.tempPromAlt1 = tempPromAlt1;
		this.desvioAlt1 = desvioAlt1;
		this.velMaxAlt1 = velMaxAlt1;
		this.dirMaxAlt1 = dirMaxAlt1;
		this.tempMaxAlt1 = tempMaxAlt1;
		this.velMinAlt1 = velMinAlt1;
		this.dirMinAlt1 = dirMinAlt1;
		this.tempMinAlt1 = tempMinAlt1;
		this.velPromAlt2 = velPromAlt2;
		this.dirPromAlt2 = dirPromAlt2;
		this.tempPromAlt2 = tempPromAlt2;
		this.desvioAlt2 = desvioAlt2;
		this.velMaxAlt2 = velMaxAlt2;
		this.dirMaxAlt2 = dirMaxAlt2;
		this.tempMaxAlt2 = tempMaxAlt2;
		this.velMinAlt2 = velMinAlt2;
		this.dirMinAlt2 = dirMinAlt2;
		this.tempMinAlt2 = tempMinAlt2;
		this.velPromAlt3 = velPromAlt3;
		this.dirPromAlt3 = dirPromAlt3;
		this.tempPromAlt3 = tempPromAlt3;
		this.desvioAlt3 = desvioAlt3;
		this.velMaxAlt3 = velMaxAlt3;
		this.dirMaxAlt3 = dirMaxAlt3;
		this.tempMaxAlt3 = tempMaxAlt3;
		this.velMinAlt3 = velMinAlt3;
		this.dirMinAlt3 = dirMinAlt3;
		this.tempMinAlt3 = tempMinAlt3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDatosTodos", unique = true, nullable = false)
	public Integer getIdDatosTodos() {
		return this.idDatosTodos;
	}

	public void setIdDatosTodos(Integer idDatosTodos) {
		this.idDatosTodos = idDatosTodos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", nullable = false, length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "tempProm", precision = 5)
	public BigDecimal getTempProm() {
		return this.tempProm;
	}

	public void setTempProm(BigDecimal tempProm) {
		this.tempProm = tempProm;
	}

	@Column(name = "humedad")
	public Integer getHumedad() {
		return this.humedad;
	}

	public void setHumedad(Integer humedad) {
		this.humedad = humedad;
	}

	@Column(name = "presion")
	public Integer getPresion() {
		return this.presion;
	}

	public void setPresion(Integer presion) {
		this.presion = presion;
	}

	@Column(name = "tempMax", precision = 5)
	public BigDecimal getTempMax() {
		return this.tempMax;
	}

	public void setTempMax(BigDecimal tempMax) {
		this.tempMax = tempMax;
	}

	@Column(name = "tempMin", precision = 5)
	public BigDecimal getTempMin() {
		return this.tempMin;
	}

	public void setTempMin(BigDecimal tempMin) {
		this.tempMin = tempMin;
	}

	@Column(name = "velPromAlt1", nullable = false, precision = 5)
	public BigDecimal getVelPromAlt1() {
		return this.velPromAlt1;
	}

	public void setVelPromAlt1(BigDecimal velPromAlt1) {
		this.velPromAlt1 = velPromAlt1;
	}

	@Column(name = "dirPromAlt1", nullable = false)
	public int getDirPromAlt1() {
		return this.dirPromAlt1;
	}

	public void setDirPromAlt1(int dirPromAlt1) {
		this.dirPromAlt1 = dirPromAlt1;
	}

	@Column(name = "tempPromAlt1", nullable = false, precision = 5)
	public BigDecimal getTempPromAlt1() {
		return this.tempPromAlt1;
	}

	public void setTempPromAlt1(BigDecimal tempPromAlt1) {
		this.tempPromAlt1 = tempPromAlt1;
	}

	@Column(name = "desvioAlt1", nullable = false, precision = 5)
	public BigDecimal getDesvioAlt1() {
		return this.desvioAlt1;
	}

	public void setDesvioAlt1(BigDecimal desvioAlt1) {
		this.desvioAlt1 = desvioAlt1;
	}

	@Column(name = "velMaxAlt1", nullable = false, precision = 5)
	public BigDecimal getVelMaxAlt1() {
		return this.velMaxAlt1;
	}

	public void setVelMaxAlt1(BigDecimal velMaxAlt1) {
		this.velMaxAlt1 = velMaxAlt1;
	}

	@Column(name = "dirMaxAlt1", nullable = false)
	public int getDirMaxAlt1() {
		return this.dirMaxAlt1;
	}

	public void setDirMaxAlt1(int dirMaxAlt1) {
		this.dirMaxAlt1 = dirMaxAlt1;
	}

	@Column(name = "tempMaxAlt1", nullable = false, precision = 5)
	public BigDecimal getTempMaxAlt1() {
		return this.tempMaxAlt1;
	}

	public void setTempMaxAlt1(BigDecimal tempMaxAlt1) {
		this.tempMaxAlt1 = tempMaxAlt1;
	}

	@Column(name = "velMinAlt1", nullable = false, precision = 5)
	public BigDecimal getVelMinAlt1() {
		return this.velMinAlt1;
	}

	public void setVelMinAlt1(BigDecimal velMinAlt1) {
		this.velMinAlt1 = velMinAlt1;
	}

	@Column(name = "dirMInAlt1", nullable = false)
	public int getDirMinAlt1() {
		return this.dirMinAlt1;
	}

	public void setDirMinAlt1(int dirMinAlt1) {
		this.dirMinAlt1 = dirMinAlt1;
	}

	@Column(name = "tempMinAlt1", nullable = false, precision = 5)
	public BigDecimal getTempMinAlt1() {
		return this.tempMinAlt1;
	}

	public void setTempMinAlt1(BigDecimal tempMinAlt1) {
		this.tempMinAlt1 = tempMinAlt1;
	}

	@Column(name = "velPromAlt2", precision = 5)
	public BigDecimal getVelPromAlt2() {
		return this.velPromAlt2;
	}

	public void setVelPromAlt2(BigDecimal velPromAlt2) {
		this.velPromAlt2 = velPromAlt2;
	}

	@Column(name = "dirPromAlt2")
	public Integer getDirPromAlt2() {
		return this.dirPromAlt2;
	}

	public void setDirPromAlt2(Integer dirPromAlt2) {
		this.dirPromAlt2 = dirPromAlt2;
	}

	@Column(name = "tempPromAlt2", precision = 5)
	public BigDecimal getTempPromAlt2() {
		return this.tempPromAlt2;
	}

	public void setTempPromAlt2(BigDecimal tempPromAlt2) {
		this.tempPromAlt2 = tempPromAlt2;
	}

	@Column(name = "desvioAlt2", precision = 5)
	public BigDecimal getDesvioAlt2() {
		return this.desvioAlt2;
	}

	public void setDesvioAlt2(BigDecimal desvioAlt2) {
		this.desvioAlt2 = desvioAlt2;
	}

	@Column(name = "velMaxAlt2", precision = 5)
	public BigDecimal getVelMaxAlt2() {
		return this.velMaxAlt2;
	}

	public void setVelMaxAlt2(BigDecimal velMaxAlt2) {
		this.velMaxAlt2 = velMaxAlt2;
	}

	@Column(name = "dirMaxAlt2")
	public Integer getDirMaxAlt2() {
		return this.dirMaxAlt2;
	}

	public void setDirMaxAlt2(Integer dirMaxAlt2) {
		this.dirMaxAlt2 = dirMaxAlt2;
	}

	@Column(name = "tempMaxAlt2", precision = 5)
	public BigDecimal getTempMaxAlt2() {
		return this.tempMaxAlt2;
	}

	public void setTempMaxAlt2(BigDecimal tempMaxAlt2) {
		this.tempMaxAlt2 = tempMaxAlt2;
	}

	@Column(name = "velMinAlt2", precision = 5)
	public BigDecimal getVelMinAlt2() {
		return this.velMinAlt2;
	}

	public void setVelMinAlt2(BigDecimal velMinAlt2) {
		this.velMinAlt2 = velMinAlt2;
	}

	@Column(name = "dirMinAlt2")
	public Integer getDirMinAlt2() {
		return this.dirMinAlt2;
	}

	public void setDirMinAlt2(Integer dirMinAlt2) {
		this.dirMinAlt2 = dirMinAlt2;
	}

	@Column(name = "tempMinAlt2", precision = 5)
	public BigDecimal getTempMinAlt2() {
		return this.tempMinAlt2;
	}

	public void setTempMinAlt2(BigDecimal tempMinAlt2) {
		this.tempMinAlt2 = tempMinAlt2;
	}

	@Column(name = "velPromAlt3", precision = 5)
	public BigDecimal getVelPromAlt3() {
		return this.velPromAlt3;
	}

	public void setVelPromAlt3(BigDecimal velPromAlt3) {
		this.velPromAlt3 = velPromAlt3;
	}

	@Column(name = "dirPromAlt3")
	public Integer getDirPromAlt3() {
		return this.dirPromAlt3;
	}

	public void setDirPromAlt3(Integer dirPromAlt3) {
		this.dirPromAlt3 = dirPromAlt3;
	}

	@Column(name = "tempPromAlt3", precision = 5)
	public BigDecimal getTempPromAlt3() {
		return this.tempPromAlt3;
	}

	public void setTempPromAlt3(BigDecimal tempPromAlt3) {
		this.tempPromAlt3 = tempPromAlt3;
	}

	@Column(name = "desvioAlt3", precision = 5)
	public BigDecimal getDesvioAlt3() {
		return this.desvioAlt3;
	}

	public void setDesvioAlt3(BigDecimal desvioAlt3) {
		this.desvioAlt3 = desvioAlt3;
	}

	@Column(name = "velMaxAlt3", precision = 5)
	public BigDecimal getVelMaxAlt3() {
		return this.velMaxAlt3;
	}

	public void setVelMaxAlt3(BigDecimal velMaxAlt3) {
		this.velMaxAlt3 = velMaxAlt3;
	}

	@Column(name = "dirMaxAlt3")
	public Integer getDirMaxAlt3() {
		return this.dirMaxAlt3;
	}

	public void setDirMaxAlt3(Integer dirMaxAlt3) {
		this.dirMaxAlt3 = dirMaxAlt3;
	}

	@Column(name = "tempMaxAlt3", precision = 5)
	public BigDecimal getTempMaxAlt3() {
		return this.tempMaxAlt3;
	}

	public void setTempMaxAlt3(BigDecimal tempMaxAlt3) {
		this.tempMaxAlt3 = tempMaxAlt3;
	}

	@Column(name = "velMinAlt3", precision = 5)
	public BigDecimal getVelMinAlt3() {
		return this.velMinAlt3;
	}

	public void setVelMinAlt3(BigDecimal velMinAlt3) {
		this.velMinAlt3 = velMinAlt3;
	}

	@Column(name = "dirMinAlt3")
	public Integer getDirMinAlt3() {
		return this.dirMinAlt3;
	}

	public void setDirMinAlt3(Integer dirMinAlt3) {
		this.dirMinAlt3 = dirMinAlt3;
	}

	@Column(name = "tempMinAlt3", precision = 5)
	public BigDecimal getTempMinAlt3() {
		return this.tempMinAlt3;
	}

	public void setTempMinAlt3(BigDecimal tempMinAlt3) {
		this.tempMinAlt3 = tempMinAlt3;
	}

}
