package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DatosPerfilTemporarioHora generated by hbm2java
 */
@Entity
@Table(name = "DatosPerfilTemporarioHora", catalog = "sgvdb")
public class DatosPerfilTemporarioHora implements java.io.Serializable {

	private Integer idDatosPerfilTemporarioHora;
	private int hora;
	private int cantidadAlt1;
	private Integer cantidadAlt2;
	private Integer cantidadAlt3;
	private double totalVelocidadPromedioAlt1;
	private Double totalVelocidadPromedioAlt2;
	private Double totalVelocidadPromedioAlt3;
	private double promedioVelocidadAlt1;
	private Double promedioVelocidadAlt2;
	private Double promedioVelocidadAlt3;
	private double totalDesvioAlt1;
	private Double totalDesvioAlt2;
	private Double totalDesvioAlt3;
	private double promedioDesvioAlt1;
	private Double promedioDesvioAlt2;
	private Double promedioDesvioAlt3;

	public DatosPerfilTemporarioHora() {
	}

	public DatosPerfilTemporarioHora(int hora, int cantidadAlt1,
			double totalVelocidadPromedioAlt1, double promedioVelocidadAlt1,
			double totalDesvioAlt1, double promedioDesvioAlt1) {
		this.hora = hora;
		this.cantidadAlt1 = cantidadAlt1;
		this.totalVelocidadPromedioAlt1 = totalVelocidadPromedioAlt1;
		this.promedioVelocidadAlt1 = promedioVelocidadAlt1;
		this.totalDesvioAlt1 = totalDesvioAlt1;
		this.promedioDesvioAlt1 = promedioDesvioAlt1;
	}

	public DatosPerfilTemporarioHora(int hora, int cantidadAlt1,
			Integer cantidadAlt2, Integer cantidadAlt3,
			double totalVelocidadPromedioAlt1,
			Double totalVelocidadPromedioAlt2,
			Double totalVelocidadPromedioAlt3, double promedioVelocidadAlt1,
			Double promedioVelocidadAlt2, Double promedioVelocidadAlt3,
			double totalDesvioAlt1, Double totalDesvioAlt2,
			Double totalDesvioAlt3, double promedioDesvioAlt1,
			Double promedioDesvioAlt2, Double promedioDesvioAlt3) {
		this.hora = hora;
		this.cantidadAlt1 = cantidadAlt1;
		this.cantidadAlt2 = cantidadAlt2;
		this.cantidadAlt3 = cantidadAlt3;
		this.totalVelocidadPromedioAlt1 = totalVelocidadPromedioAlt1;
		this.totalVelocidadPromedioAlt2 = totalVelocidadPromedioAlt2;
		this.totalVelocidadPromedioAlt3 = totalVelocidadPromedioAlt3;
		this.promedioVelocidadAlt1 = promedioVelocidadAlt1;
		this.promedioVelocidadAlt2 = promedioVelocidadAlt2;
		this.promedioVelocidadAlt3 = promedioVelocidadAlt3;
		this.totalDesvioAlt1 = totalDesvioAlt1;
		this.totalDesvioAlt2 = totalDesvioAlt2;
		this.totalDesvioAlt3 = totalDesvioAlt3;
		this.promedioDesvioAlt1 = promedioDesvioAlt1;
		this.promedioDesvioAlt2 = promedioDesvioAlt2;
		this.promedioDesvioAlt3 = promedioDesvioAlt3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDatosPerfilTemporarioHora", unique = true, nullable = false)
	public Integer getIdDatosPerfilTemporarioHora() {
		return this.idDatosPerfilTemporarioHora;
	}

	public void setIdDatosPerfilTemporarioHora(
			Integer idDatosPerfilTemporarioHora) {
		this.idDatosPerfilTemporarioHora = idDatosPerfilTemporarioHora;
	}

	@Column(name = "hora", nullable = false)
	public int getHora() {
		return this.hora;
	}

	public void setHora(int hora) {
		this.hora = hora;
	}

	@Column(name = "cantidadAlt1", nullable = false)
	public int getCantidadAlt1() {
		return this.cantidadAlt1;
	}

	public void setCantidadAlt1(int cantidadAlt1) {
		this.cantidadAlt1 = cantidadAlt1;
	}

	@Column(name = "cantidadAlt2")
	public Integer getCantidadAlt2() {
		return this.cantidadAlt2;
	}

	public void setCantidadAlt2(Integer cantidadAlt2) {
		this.cantidadAlt2 = cantidadAlt2;
	}

	@Column(name = "cantidadAlt3")
	public Integer getCantidadAlt3() {
		return this.cantidadAlt3;
	}

	public void setCantidadAlt3(Integer cantidadAlt3) {
		this.cantidadAlt3 = cantidadAlt3;
	}

	@Column(name = "totalVelocidadPromedioAlt1", nullable = false, precision = 22, scale = 0)
	public double getTotalVelocidadPromedioAlt1() {
		return this.totalVelocidadPromedioAlt1;
	}

	public void setTotalVelocidadPromedioAlt1(double totalVelocidadPromedioAlt1) {
		this.totalVelocidadPromedioAlt1 = totalVelocidadPromedioAlt1;
	}

	@Column(name = "totalVelocidadPromedioAlt2", precision = 22, scale = 0)
	public Double getTotalVelocidadPromedioAlt2() {
		return this.totalVelocidadPromedioAlt2;
	}

	public void setTotalVelocidadPromedioAlt2(Double totalVelocidadPromedioAlt2) {
		this.totalVelocidadPromedioAlt2 = totalVelocidadPromedioAlt2;
	}

	@Column(name = "totalVelocidadPromedioAlt3", precision = 22, scale = 0)
	public Double getTotalVelocidadPromedioAlt3() {
		return this.totalVelocidadPromedioAlt3;
	}

	public void setTotalVelocidadPromedioAlt3(Double totalVelocidadPromedioAlt3) {
		this.totalVelocidadPromedioAlt3 = totalVelocidadPromedioAlt3;
	}

	@Column(name = "promedioVelocidadAlt1", nullable = false, precision = 22, scale = 0)
	public double getPromedioVelocidadAlt1() {
		return this.promedioVelocidadAlt1;
	}

	public void setPromedioVelocidadAlt1(double promedioVelocidadAlt1) {
		this.promedioVelocidadAlt1 = promedioVelocidadAlt1;
	}

	@Column(name = "promedioVelocidadAlt2", precision = 22, scale = 0)
	public Double getPromedioVelocidadAlt2() {
		return this.promedioVelocidadAlt2;
	}

	public void setPromedioVelocidadAlt2(Double promedioVelocidadAlt2) {
		this.promedioVelocidadAlt2 = promedioVelocidadAlt2;
	}

	@Column(name = "promedioVelocidadAlt3", precision = 22, scale = 0)
	public Double getPromedioVelocidadAlt3() {
		return this.promedioVelocidadAlt3;
	}

	public void setPromedioVelocidadAlt3(Double promedioVelocidadAlt3) {
		this.promedioVelocidadAlt3 = promedioVelocidadAlt3;
	}

	@Column(name = "totalDesvioAlt1", nullable = false, precision = 22, scale = 0)
	public double getTotalDesvioAlt1() {
		return this.totalDesvioAlt1;
	}

	public void setTotalDesvioAlt1(double totalDesvioAlt1) {
		this.totalDesvioAlt1 = totalDesvioAlt1;
	}

	@Column(name = "totalDesvioAlt2", precision = 22, scale = 0)
	public Double getTotalDesvioAlt2() {
		return this.totalDesvioAlt2;
	}

	public void setTotalDesvioAlt2(Double totalDesvioAlt2) {
		this.totalDesvioAlt2 = totalDesvioAlt2;
	}

	@Column(name = "totalDesvioAlt3", precision = 22, scale = 0)
	public Double getTotalDesvioAlt3() {
		return this.totalDesvioAlt3;
	}

	public void setTotalDesvioAlt3(Double totalDesvioAlt3) {
		this.totalDesvioAlt3 = totalDesvioAlt3;
	}

	@Column(name = "promedioDesvioAlt1", nullable = false, precision = 22, scale = 0)
	public double getPromedioDesvioAlt1() {
		return this.promedioDesvioAlt1;
	}

	public void setPromedioDesvioAlt1(double promedioDesvioAlt1) {
		this.promedioDesvioAlt1 = promedioDesvioAlt1;
	}

	@Column(name = "promedioDesvioAlt2", precision = 22, scale = 0)
	public Double getPromedioDesvioAlt2() {
		return this.promedioDesvioAlt2;
	}

	public void setPromedioDesvioAlt2(Double promedioDesvioAlt2) {
		this.promedioDesvioAlt2 = promedioDesvioAlt2;
	}

	@Column(name = "promedioDesvioAlt3", precision = 22, scale = 0)
	public Double getPromedioDesvioAlt3() {
		return this.promedioDesvioAlt3;
	}

	public void setPromedioDesvioAlt3(Double promedioDesvioAlt3) {
		this.promedioDesvioAlt3 = promedioDesvioAlt3;
	}

}
