package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DatosFrecuenciaVelocidad generated by hbm2java
 */
@Entity
@Table(name = "DatosFrecuenciaVelocidad", catalog = "sgvdb")
public class DatosFrecuenciaVelocidad implements java.io.Serializable {

	private Integer idDatosFrecuenciaVelocidad;
	private double velocidad;
	private Integer cantDatosAlt1;
	private Integer cantDatosAlt2;
	private Integer cantDatosAlt3;
	private Double porcentajeAlt1;
	private Double porcentajeAlt2;
	private Double porcentajeAlt3;

	public DatosFrecuenciaVelocidad() {
	}

	public DatosFrecuenciaVelocidad(double velocidad) {
		this.velocidad = velocidad;
	}

	public DatosFrecuenciaVelocidad(double velocidad, Integer cantDatosAlt1,
			Integer cantDatosAlt2, Integer cantDatosAlt3,
			Double porcentajeAlt1, Double porcentajeAlt2, Double porcentajeAlt3) {
		this.velocidad = velocidad;
		this.cantDatosAlt1 = cantDatosAlt1;
		this.cantDatosAlt2 = cantDatosAlt2;
		this.cantDatosAlt3 = cantDatosAlt3;
		this.porcentajeAlt1 = porcentajeAlt1;
		this.porcentajeAlt2 = porcentajeAlt2;
		this.porcentajeAlt3 = porcentajeAlt3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDatosFrecuenciaVelocidad", unique = true, nullable = false)
	public Integer getIdDatosFrecuenciaVelocidad() {
		return this.idDatosFrecuenciaVelocidad;
	}

	public void setIdDatosFrecuenciaVelocidad(Integer idDatosFrecuenciaVelocidad) {
		this.idDatosFrecuenciaVelocidad = idDatosFrecuenciaVelocidad;
	}

	@Column(name = "velocidad", nullable = false, precision = 22, scale = 0)
	public double getVelocidad() {
		return this.velocidad;
	}

	public void setVelocidad(double velocidad) {
		this.velocidad = velocidad;
	}

	@Column(name = "cantDatosAlt1")
	public Integer getCantDatosAlt1() {
		return this.cantDatosAlt1;
	}

	public void setCantDatosAlt1(Integer cantDatosAlt1) {
		this.cantDatosAlt1 = cantDatosAlt1;
	}

	@Column(name = "cantDatosAlt2")
	public Integer getCantDatosAlt2() {
		return this.cantDatosAlt2;
	}

	public void setCantDatosAlt2(Integer cantDatosAlt2) {
		this.cantDatosAlt2 = cantDatosAlt2;
	}

	@Column(name = "cantDatosAlt3")
	public Integer getCantDatosAlt3() {
		return this.cantDatosAlt3;
	}

	public void setCantDatosAlt3(Integer cantDatosAlt3) {
		this.cantDatosAlt3 = cantDatosAlt3;
	}

	@Column(name = "porcentajeAlt1", precision = 22, scale = 0)
	public Double getPorcentajeAlt1() {
		return this.porcentajeAlt1;
	}

	public void setPorcentajeAlt1(Double porcentajeAlt1) {
		this.porcentajeAlt1 = porcentajeAlt1;
	}

	@Column(name = "porcentajeAlt2", precision = 22, scale = 0)
	public Double getPorcentajeAlt2() {
		return this.porcentajeAlt2;
	}

	public void setPorcentajeAlt2(Double porcentajeAlt2) {
		this.porcentajeAlt2 = porcentajeAlt2;
	}

	@Column(name = "porcentajeAlt3", precision = 22, scale = 0)
	public Double getPorcentajeAlt3() {
		return this.porcentajeAlt3;
	}

	public void setPorcentajeAlt3(Double porcentajeAlt3) {
		this.porcentajeAlt3 = porcentajeAlt3;
	}

}
