package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DatosPerfilVertical generated by hbm2java
 */
@Entity
@Table(name = "DatosPerfilVertical", catalog = "sgvdb")
public class DatosPerfilVertical implements java.io.Serializable {

	private Integer idDatosPerfilVertical;
	private int altura;
	private int cantidadXrenglon;
	private double totalVelocidadPromedio;
	private double totalTempPromedio;
	private double promedioVelocidadRenglon;
	private double promedioTempRenglon;

	public DatosPerfilVertical() {
	}

	public DatosPerfilVertical(int altura, int cantidadXrenglon,
			double totalVelocidadPromedio, double totalTempPromedio,
			double promedioVelocidadRenglon, double promedioTempRenglon) {
		this.altura = altura;
		this.cantidadXrenglon = cantidadXrenglon;
		this.totalVelocidadPromedio = totalVelocidadPromedio;
		this.totalTempPromedio = totalTempPromedio;
		this.promedioVelocidadRenglon = promedioVelocidadRenglon;
		this.promedioTempRenglon = promedioTempRenglon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDatosPerfilVertical", unique = true, nullable = false)
	public Integer getIdDatosPerfilVertical() {
		return this.idDatosPerfilVertical;
	}

	public void setIdDatosPerfilVertical(Integer idDatosPerfilVertical) {
		this.idDatosPerfilVertical = idDatosPerfilVertical;
	}

	@Column(name = "altura", nullable = false)
	public int getAltura() {
		return this.altura;
	}

	public void setAltura(int altura) {
		this.altura = altura;
	}

	@Column(name = "cantidadXRenglon", nullable = false)
	public int getCantidadXrenglon() {
		return this.cantidadXrenglon;
	}

	public void setCantidadXrenglon(int cantidadXrenglon) {
		this.cantidadXrenglon = cantidadXrenglon;
	}

	@Column(name = "totalVelocidadPromedio", nullable = false, precision = 22, scale = 0)
	public double getTotalVelocidadPromedio() {
		return this.totalVelocidadPromedio;
	}

	public void setTotalVelocidadPromedio(double totalVelocidadPromedio) {
		this.totalVelocidadPromedio = totalVelocidadPromedio;
	}

	@Column(name = "totalTempPromedio", nullable = false, precision = 22, scale = 0)
	public double getTotalTempPromedio() {
		return this.totalTempPromedio;
	}

	public void setTotalTempPromedio(double totalTempPromedio) {
		this.totalTempPromedio = totalTempPromedio;
	}

	@Column(name = "promedioVelocidadRenglon", nullable = false, precision = 22, scale = 0)
	public double getPromedioVelocidadRenglon() {
		return this.promedioVelocidadRenglon;
	}

	public void setPromedioVelocidadRenglon(double promedioVelocidadRenglon) {
		this.promedioVelocidadRenglon = promedioVelocidadRenglon;
	}

	@Column(name = "promedioTempRenglon", nullable = false, precision = 22, scale = 0)
	public double getPromedioTempRenglon() {
		return this.promedioTempRenglon;
	}

	public void setPromedioTempRenglon(double promedioTempRenglon) {
		this.promedioTempRenglon = promedioTempRenglon;
	}

}
