package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DireccionVientoRangos generated by hbm2java
 */
@Entity
@Table(name = "DireccionVientoRangos", catalog = "sgvdb")
public class DireccionVientoRangos implements java.io.Serializable {

	private Integer idDireccionVientoRangos;
	private int division;
	private BigDecimal inicioRango;
	private BigDecimal finRango;
	private Integer cantDatosAlt1;
	private Integer cantDatosAlt2;
	private Integer cantDatosAlt3;
	private Double porcentajeAlt1;
	private Double porcentajeAlt2;
	private Double porcentajeAlt3;

	public DireccionVientoRangos() {
	}

	public DireccionVientoRangos(int division, BigDecimal inicioRango,
			BigDecimal finRango) {
		this.division = division;
		this.inicioRango = inicioRango;
		this.finRango = finRango;
	}

	public DireccionVientoRangos(int division, BigDecimal inicioRango,
			BigDecimal finRango, Integer cantDatosAlt1, Integer cantDatosAlt2,
			Integer cantDatosAlt3, Double porcentajeAlt1,
			Double porcentajeAlt2, Double porcentajeAlt3) {
		this.division = division;
		this.inicioRango = inicioRango;
		this.finRango = finRango;
		this.cantDatosAlt1 = cantDatosAlt1;
		this.cantDatosAlt2 = cantDatosAlt2;
		this.cantDatosAlt3 = cantDatosAlt3;
		this.porcentajeAlt1 = porcentajeAlt1;
		this.porcentajeAlt2 = porcentajeAlt2;
		this.porcentajeAlt3 = porcentajeAlt3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDireccionVientoRangos", unique = true, nullable = false)
	public Integer getIdDireccionVientoRangos() {
		return this.idDireccionVientoRangos;
	}

	public void setIdDireccionVientoRangos(Integer idDireccionVientoRangos) {
		this.idDireccionVientoRangos = idDireccionVientoRangos;
	}

	@Column(name = "division", nullable = false)
	public int getDivision() {
		return this.division;
	}

	public void setDivision(int division) {
		this.division = division;
	}

	@Column(name = "inicioRango", nullable = false, precision = 5)
	public BigDecimal getInicioRango() {
		return this.inicioRango;
	}

	public void setInicioRango(BigDecimal inicioRango) {
		this.inicioRango = inicioRango;
	}

	@Column(name = "finRango", nullable = false, precision = 5)
	public BigDecimal getFinRango() {
		return this.finRango;
	}

	public void setFinRango(BigDecimal finRango) {
		this.finRango = finRango;
	}

	@Column(name = "cantDatosAlt1")
	public Integer getCantDatosAlt1() {
		return this.cantDatosAlt1;
	}

	public void setCantDatosAlt1(Integer cantDatosAlt1) {
		this.cantDatosAlt1 = cantDatosAlt1;
	}

	@Column(name = "cantDatosAlt2")
	public Integer getCantDatosAlt2() {
		return this.cantDatosAlt2;
	}

	public void setCantDatosAlt2(Integer cantDatosAlt2) {
		this.cantDatosAlt2 = cantDatosAlt2;
	}

	@Column(name = "cantDatosAlt3")
	public Integer getCantDatosAlt3() {
		return this.cantDatosAlt3;
	}

	public void setCantDatosAlt3(Integer cantDatosAlt3) {
		this.cantDatosAlt3 = cantDatosAlt3;
	}

	@Column(name = "porcentajeAlt1", precision = 22, scale = 0)
	public Double getPorcentajeAlt1() {
		return this.porcentajeAlt1;
	}

	public void setPorcentajeAlt1(Double porcentajeAlt1) {
		this.porcentajeAlt1 = porcentajeAlt1;
	}

	@Column(name = "porcentajeAlt2", precision = 22, scale = 0)
	public Double getPorcentajeAlt2() {
		return this.porcentajeAlt2;
	}

	public void setPorcentajeAlt2(Double porcentajeAlt2) {
		this.porcentajeAlt2 = porcentajeAlt2;
	}

	@Column(name = "porcentajeAlt3", precision = 22, scale = 0)
	public Double getPorcentajeAlt3() {
		return this.porcentajeAlt3;
	}

	public void setPorcentajeAlt3(Double porcentajeAlt3) {
		this.porcentajeAlt3 = porcentajeAlt3;
	}

}
