package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewDatosAltura3Id generated by hbm2java
 */
@Embeddable
public class ViewDatosAltura3Id implements java.io.Serializable {

	private int idDatosTodos;
	private Date fecha;
	private Date hora;
	private BigDecimal velPromAlt3;
	private Integer dirPromAlt3;
	private BigDecimal tempPromAlt3;
	private BigDecimal desvioAlt3;
	private BigDecimal velMaxAlt3;
	private Integer dirMaxAlt3;
	private BigDecimal tempMaxAlt3;
	private BigDecimal velMinAlt3;
	private Integer dirMinAlt3;
	private BigDecimal tempMinAlt3;

	public ViewDatosAltura3Id() {
	}

	public ViewDatosAltura3Id(int idDatosTodos, Date fecha, Date hora) {
		this.idDatosTodos = idDatosTodos;
		this.fecha = fecha;
		this.hora = hora;
	}

	public ViewDatosAltura3Id(int idDatosTodos, Date fecha, Date hora,
			BigDecimal velPromAlt3, Integer dirPromAlt3,
			BigDecimal tempPromAlt3, BigDecimal desvioAlt3,
			BigDecimal velMaxAlt3, Integer dirMaxAlt3, BigDecimal tempMaxAlt3,
			BigDecimal velMinAlt3, Integer dirMinAlt3, BigDecimal tempMinAlt3) {
		this.idDatosTodos = idDatosTodos;
		this.fecha = fecha;
		this.hora = hora;
		this.velPromAlt3 = velPromAlt3;
		this.dirPromAlt3 = dirPromAlt3;
		this.tempPromAlt3 = tempPromAlt3;
		this.desvioAlt3 = desvioAlt3;
		this.velMaxAlt3 = velMaxAlt3;
		this.dirMaxAlt3 = dirMaxAlt3;
		this.tempMaxAlt3 = tempMaxAlt3;
		this.velMinAlt3 = velMinAlt3;
		this.dirMinAlt3 = dirMinAlt3;
		this.tempMinAlt3 = tempMinAlt3;
	}

	@Column(name = "idDatosTodos", nullable = false)
	public int getIdDatosTodos() {
		return this.idDatosTodos;
	}

	public void setIdDatosTodos(int idDatosTodos) {
		this.idDatosTodos = idDatosTodos;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "hora", nullable = false, length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "velPromAlt3", precision = 5)
	public BigDecimal getVelPromAlt3() {
		return this.velPromAlt3;
	}

	public void setVelPromAlt3(BigDecimal velPromAlt3) {
		this.velPromAlt3 = velPromAlt3;
	}

	@Column(name = "dirPromAlt3")
	public Integer getDirPromAlt3() {
		return this.dirPromAlt3;
	}

	public void setDirPromAlt3(Integer dirPromAlt3) {
		this.dirPromAlt3 = dirPromAlt3;
	}

	@Column(name = "tempPromAlt3", precision = 5)
	public BigDecimal getTempPromAlt3() {
		return this.tempPromAlt3;
	}

	public void setTempPromAlt3(BigDecimal tempPromAlt3) {
		this.tempPromAlt3 = tempPromAlt3;
	}

	@Column(name = "desvioAlt3", precision = 5)
	public BigDecimal getDesvioAlt3() {
		return this.desvioAlt3;
	}

	public void setDesvioAlt3(BigDecimal desvioAlt3) {
		this.desvioAlt3 = desvioAlt3;
	}

	@Column(name = "velMaxAlt3", precision = 5)
	public BigDecimal getVelMaxAlt3() {
		return this.velMaxAlt3;
	}

	public void setVelMaxAlt3(BigDecimal velMaxAlt3) {
		this.velMaxAlt3 = velMaxAlt3;
	}

	@Column(name = "dirMaxAlt3")
	public Integer getDirMaxAlt3() {
		return this.dirMaxAlt3;
	}

	public void setDirMaxAlt3(Integer dirMaxAlt3) {
		this.dirMaxAlt3 = dirMaxAlt3;
	}

	@Column(name = "tempMaxAlt3", precision = 5)
	public BigDecimal getTempMaxAlt3() {
		return this.tempMaxAlt3;
	}

	public void setTempMaxAlt3(BigDecimal tempMaxAlt3) {
		this.tempMaxAlt3 = tempMaxAlt3;
	}

	@Column(name = "velMinAlt3", precision = 5)
	public BigDecimal getVelMinAlt3() {
		return this.velMinAlt3;
	}

	public void setVelMinAlt3(BigDecimal velMinAlt3) {
		this.velMinAlt3 = velMinAlt3;
	}

	@Column(name = "dirMinAlt3")
	public Integer getDirMinAlt3() {
		return this.dirMinAlt3;
	}

	public void setDirMinAlt3(Integer dirMinAlt3) {
		this.dirMinAlt3 = dirMinAlt3;
	}

	@Column(name = "tempMinAlt3", precision = 5)
	public BigDecimal getTempMinAlt3() {
		return this.tempMinAlt3;
	}

	public void setTempMinAlt3(BigDecimal tempMinAlt3) {
		this.tempMinAlt3 = tempMinAlt3;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewDatosAltura3Id))
			return false;
		ViewDatosAltura3Id castOther = (ViewDatosAltura3Id) other;

		return (this.getIdDatosTodos() == castOther.getIdDatosTodos())
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora()
						.equals(castOther.getHora())))
				&& ((this.getVelPromAlt3() == castOther.getVelPromAlt3()) || (this
						.getVelPromAlt3() != null
						&& castOther.getVelPromAlt3() != null && this
						.getVelPromAlt3().equals(castOther.getVelPromAlt3())))
				&& ((this.getDirPromAlt3() == castOther.getDirPromAlt3()) || (this
						.getDirPromAlt3() != null
						&& castOther.getDirPromAlt3() != null && this
						.getDirPromAlt3().equals(castOther.getDirPromAlt3())))
				&& ((this.getTempPromAlt3() == castOther.getTempPromAlt3()) || (this
						.getTempPromAlt3() != null
						&& castOther.getTempPromAlt3() != null && this
						.getTempPromAlt3().equals(castOther.getTempPromAlt3())))
				&& ((this.getDesvioAlt3() == castOther.getDesvioAlt3()) || (this
						.getDesvioAlt3() != null
						&& castOther.getDesvioAlt3() != null && this
						.getDesvioAlt3().equals(castOther.getDesvioAlt3())))
				&& ((this.getVelMaxAlt3() == castOther.getVelMaxAlt3()) || (this
						.getVelMaxAlt3() != null
						&& castOther.getVelMaxAlt3() != null && this
						.getVelMaxAlt3().equals(castOther.getVelMaxAlt3())))
				&& ((this.getDirMaxAlt3() == castOther.getDirMaxAlt3()) || (this
						.getDirMaxAlt3() != null
						&& castOther.getDirMaxAlt3() != null && this
						.getDirMaxAlt3().equals(castOther.getDirMaxAlt3())))
				&& ((this.getTempMaxAlt3() == castOther.getTempMaxAlt3()) || (this
						.getTempMaxAlt3() != null
						&& castOther.getTempMaxAlt3() != null && this
						.getTempMaxAlt3().equals(castOther.getTempMaxAlt3())))
				&& ((this.getVelMinAlt3() == castOther.getVelMinAlt3()) || (this
						.getVelMinAlt3() != null
						&& castOther.getVelMinAlt3() != null && this
						.getVelMinAlt3().equals(castOther.getVelMinAlt3())))
				&& ((this.getDirMinAlt3() == castOther.getDirMinAlt3()) || (this
						.getDirMinAlt3() != null
						&& castOther.getDirMinAlt3() != null && this
						.getDirMinAlt3().equals(castOther.getDirMinAlt3())))
				&& ((this.getTempMinAlt3() == castOther.getTempMinAlt3()) || (this
						.getTempMinAlt3() != null
						&& castOther.getTempMinAlt3() != null && this
						.getTempMinAlt3().equals(castOther.getTempMinAlt3())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDatosTodos();
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37
				* result
				+ (getVelPromAlt3() == null ? 0 : this.getVelPromAlt3()
						.hashCode());
		result = 37
				* result
				+ (getDirPromAlt3() == null ? 0 : this.getDirPromAlt3()
						.hashCode());
		result = 37
				* result
				+ (getTempPromAlt3() == null ? 0 : this.getTempPromAlt3()
						.hashCode());
		result = 37
				* result
				+ (getDesvioAlt3() == null ? 0 : this.getDesvioAlt3()
						.hashCode());
		result = 37
				* result
				+ (getVelMaxAlt3() == null ? 0 : this.getVelMaxAlt3()
						.hashCode());
		result = 37
				* result
				+ (getDirMaxAlt3() == null ? 0 : this.getDirMaxAlt3()
						.hashCode());
		result = 37
				* result
				+ (getTempMaxAlt3() == null ? 0 : this.getTempMaxAlt3()
						.hashCode());
		result = 37
				* result
				+ (getVelMinAlt3() == null ? 0 : this.getVelMinAlt3()
						.hashCode());
		result = 37
				* result
				+ (getDirMinAlt3() == null ? 0 : this.getDirMinAlt3()
						.hashCode());
		result = 37
				* result
				+ (getTempMinAlt3() == null ? 0 : this.getTempMinAlt3()
						.hashCode());
		return result;
	}

}
