package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewDatosComunes generated by hbm2java
 */
@Entity
@Table(name = "ViewDatosComunes", catalog = "sgvdb")
public class ViewDatosComunes implements java.io.Serializable {

	private ViewDatosComunesId id;

	public ViewDatosComunes() {
	}

	public ViewDatosComunes(ViewDatosComunesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDatosTodos", column = @Column(name = "idDatosTodos", nullable = false)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 10)),
			@AttributeOverride(name = "hora", column = @Column(name = "hora", nullable = false, length = 8)),
			@AttributeOverride(name = "tempProm", column = @Column(name = "tempProm", precision = 5)),
			@AttributeOverride(name = "humedad", column = @Column(name = "humedad")),
			@AttributeOverride(name = "presion", column = @Column(name = "presion")),
			@AttributeOverride(name = "tempMax", column = @Column(name = "tempMax", precision = 5)),
			@AttributeOverride(name = "tempMin", column = @Column(name = "tempMin", precision = 5)) })
	public ViewDatosComunesId getId() {
		return this.id;
	}

	public void setId(ViewDatosComunesId id) {
		this.id = id;
	}

}
