package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewDatosAltura2 generated by hbm2java
 */
@Entity
@Table(name = "ViewDatosAltura2", catalog = "sgvdb")
public class ViewDatosAltura2 implements java.io.Serializable {

	private ViewDatosAltura2Id id;

	public ViewDatosAltura2() {
	}

	public ViewDatosAltura2(ViewDatosAltura2Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDatosTodos", column = @Column(name = "idDatosTodos", nullable = false)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 10)),
			@AttributeOverride(name = "hora", column = @Column(name = "hora", nullable = false, length = 8)),
			@AttributeOverride(name = "velPromAlt2", column = @Column(name = "velPromAlt2", precision = 5)),
			@AttributeOverride(name = "dirPromAlt2", column = @Column(name = "dirPromAlt2")),
			@AttributeOverride(name = "tempPromAlt2", column = @Column(name = "tempPromAlt2", precision = 5)),
			@AttributeOverride(name = "desvioAlt2", column = @Column(name = "desvioAlt2", precision = 5)),
			@AttributeOverride(name = "velMaxAlt2", column = @Column(name = "velMaxAlt2", precision = 5)),
			@AttributeOverride(name = "dirMaxAlt2", column = @Column(name = "dirMaxAlt2")),
			@AttributeOverride(name = "tempMaxAlt2", column = @Column(name = "tempMaxAlt2", precision = 5)),
			@AttributeOverride(name = "velMinAlt2", column = @Column(name = "velMinAlt2", precision = 5)),
			@AttributeOverride(name = "dirMinAlt2", column = @Column(name = "dirMinAlt2")),
			@AttributeOverride(name = "tempMinAlt2", column = @Column(name = "tempMinAlt2", precision = 5)) })
	public ViewDatosAltura2Id getId() {
		return this.id;
	}

	public void setId(ViewDatosAltura2Id id) {
		this.id = id;
	}

}
