package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewDatosAltura1 generated by hbm2java
 */
@Entity
@Table(name = "ViewDatosAltura1", catalog = "sgvdb")
public class ViewDatosAltura1 implements java.io.Serializable {

	private ViewDatosAltura1Id id;

	public ViewDatosAltura1() {
	}

	public ViewDatosAltura1(ViewDatosAltura1Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDatosTodos", column = @Column(name = "idDatosTodos", nullable = false)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 10)),
			@AttributeOverride(name = "hora", column = @Column(name = "hora", nullable = false, length = 8)),
			@AttributeOverride(name = "velPromAlt1", column = @Column(name = "velPromAlt1", nullable = false, precision = 5)),
			@AttributeOverride(name = "dirPromAlt1", column = @Column(name = "dirPromAlt1", nullable = false)),
			@AttributeOverride(name = "tempPromAlt1", column = @Column(name = "tempPromAlt1", nullable = false, precision = 5)),
			@AttributeOverride(name = "desvioAlt1", column = @Column(name = "desvioAlt1", nullable = false, precision = 5)),
			@AttributeOverride(name = "velMaxAlt1", column = @Column(name = "velMaxAlt1", nullable = false, precision = 5)),
			@AttributeOverride(name = "dirMaxAlt1", column = @Column(name = "dirMaxAlt1", nullable = false)),
			@AttributeOverride(name = "tempMaxAlt1", column = @Column(name = "tempMaxAlt1", nullable = false, precision = 5)),
			@AttributeOverride(name = "velMinAlt1", column = @Column(name = "velMinAlt1", nullable = false, precision = 5)),
			@AttributeOverride(name = "dirMinAlt1", column = @Column(name = "dirMinAlt1", nullable = false)),
			@AttributeOverride(name = "tempMinAlt1", column = @Column(name = "tempMinAlt1", nullable = false, precision = 5)) })
	public ViewDatosAltura1Id getId() {
		return this.id;
	}

	public void setId(ViewDatosAltura1Id id) {
		this.id = id;
	}

}
