package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewDatosAltura1Id generated by hbm2java
 */
@Embeddable
public class ViewDatosAltura1Id implements java.io.Serializable {

	private int idDatosTodos;
	private Date fecha;
	private Date hora;
	private BigDecimal velPromAlt1;
	private int dirPromAlt1;
	private BigDecimal tempPromAlt1;
	private BigDecimal desvioAlt1;
	private BigDecimal velMaxAlt1;
	private int dirMaxAlt1;
	private BigDecimal tempMaxAlt1;
	private BigDecimal velMinAlt1;
	private int dirMinAlt1;
	private BigDecimal tempMinAlt1;

	public ViewDatosAltura1Id() {
	}

	public ViewDatosAltura1Id(int idDatosTodos, Date fecha, Date hora,
			BigDecimal velPromAlt1, int dirPromAlt1, BigDecimal tempPromAlt1,
			BigDecimal desvioAlt1, BigDecimal velMaxAlt1, int dirMaxAlt1,
			BigDecimal tempMaxAlt1, BigDecimal velMinAlt1, int dirMinAlt1,
			BigDecimal tempMinAlt1) {
		this.idDatosTodos = idDatosTodos;
		this.fecha = fecha;
		this.hora = hora;
		this.velPromAlt1 = velPromAlt1;
		this.dirPromAlt1 = dirPromAlt1;
		this.tempPromAlt1 = tempPromAlt1;
		this.desvioAlt1 = desvioAlt1;
		this.velMaxAlt1 = velMaxAlt1;
		this.dirMaxAlt1 = dirMaxAlt1;
		this.tempMaxAlt1 = tempMaxAlt1;
		this.velMinAlt1 = velMinAlt1;
		this.dirMinAlt1 = dirMinAlt1;
		this.tempMinAlt1 = tempMinAlt1;
	}

	@Column(name = "idDatosTodos", nullable = false)
	public int getIdDatosTodos() {
		return this.idDatosTodos;
	}

	public void setIdDatosTodos(int idDatosTodos) {
		this.idDatosTodos = idDatosTodos;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "hora", nullable = false, length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "velPromAlt1", nullable = false, precision = 5)
	public BigDecimal getVelPromAlt1() {
		return this.velPromAlt1;
	}

	public void setVelPromAlt1(BigDecimal velPromAlt1) {
		this.velPromAlt1 = velPromAlt1;
	}

	@Column(name = "dirPromAlt1", nullable = false)
	public int getDirPromAlt1() {
		return this.dirPromAlt1;
	}

	public void setDirPromAlt1(int dirPromAlt1) {
		this.dirPromAlt1 = dirPromAlt1;
	}

	@Column(name = "tempPromAlt1", nullable = false, precision = 5)
	public BigDecimal getTempPromAlt1() {
		return this.tempPromAlt1;
	}

	public void setTempPromAlt1(BigDecimal tempPromAlt1) {
		this.tempPromAlt1 = tempPromAlt1;
	}

	@Column(name = "desvioAlt1", nullable = false, precision = 5)
	public BigDecimal getDesvioAlt1() {
		return this.desvioAlt1;
	}

	public void setDesvioAlt1(BigDecimal desvioAlt1) {
		this.desvioAlt1 = desvioAlt1;
	}

	@Column(name = "velMaxAlt1", nullable = false, precision = 5)
	public BigDecimal getVelMaxAlt1() {
		return this.velMaxAlt1;
	}

	public void setVelMaxAlt1(BigDecimal velMaxAlt1) {
		this.velMaxAlt1 = velMaxAlt1;
	}

	@Column(name = "dirMaxAlt1", nullable = false)
	public int getDirMaxAlt1() {
		return this.dirMaxAlt1;
	}

	public void setDirMaxAlt1(int dirMaxAlt1) {
		this.dirMaxAlt1 = dirMaxAlt1;
	}

	@Column(name = "tempMaxAlt1", nullable = false, precision = 5)
	public BigDecimal getTempMaxAlt1() {
		return this.tempMaxAlt1;
	}

	public void setTempMaxAlt1(BigDecimal tempMaxAlt1) {
		this.tempMaxAlt1 = tempMaxAlt1;
	}

	@Column(name = "velMinAlt1", nullable = false, precision = 5)
	public BigDecimal getVelMinAlt1() {
		return this.velMinAlt1;
	}

	public void setVelMinAlt1(BigDecimal velMinAlt1) {
		this.velMinAlt1 = velMinAlt1;
	}

	@Column(name = "dirMinAlt1", nullable = false)
	public int getDirMinAlt1() {
		return this.dirMinAlt1;
	}

	public void setDirMinAlt1(int dirMinAlt1) {
		this.dirMinAlt1 = dirMinAlt1;
	}

	@Column(name = "tempMinAlt1", nullable = false, precision = 5)
	public BigDecimal getTempMinAlt1() {
		return this.tempMinAlt1;
	}

	public void setTempMinAlt1(BigDecimal tempMinAlt1) {
		this.tempMinAlt1 = tempMinAlt1;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewDatosAltura1Id))
			return false;
		ViewDatosAltura1Id castOther = (ViewDatosAltura1Id) other;

		return (this.getIdDatosTodos() == castOther.getIdDatosTodos())
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora()
						.equals(castOther.getHora())))
				&& ((this.getVelPromAlt1() == castOther.getVelPromAlt1()) || (this
						.getVelPromAlt1() != null
						&& castOther.getVelPromAlt1() != null && this
						.getVelPromAlt1().equals(castOther.getVelPromAlt1())))
				&& (this.getDirPromAlt1() == castOther.getDirPromAlt1())
				&& ((this.getTempPromAlt1() == castOther.getTempPromAlt1()) || (this
						.getTempPromAlt1() != null
						&& castOther.getTempPromAlt1() != null && this
						.getTempPromAlt1().equals(castOther.getTempPromAlt1())))
				&& ((this.getDesvioAlt1() == castOther.getDesvioAlt1()) || (this
						.getDesvioAlt1() != null
						&& castOther.getDesvioAlt1() != null && this
						.getDesvioAlt1().equals(castOther.getDesvioAlt1())))
				&& ((this.getVelMaxAlt1() == castOther.getVelMaxAlt1()) || (this
						.getVelMaxAlt1() != null
						&& castOther.getVelMaxAlt1() != null && this
						.getVelMaxAlt1().equals(castOther.getVelMaxAlt1())))
				&& (this.getDirMaxAlt1() == castOther.getDirMaxAlt1())
				&& ((this.getTempMaxAlt1() == castOther.getTempMaxAlt1()) || (this
						.getTempMaxAlt1() != null
						&& castOther.getTempMaxAlt1() != null && this
						.getTempMaxAlt1().equals(castOther.getTempMaxAlt1())))
				&& ((this.getVelMinAlt1() == castOther.getVelMinAlt1()) || (this
						.getVelMinAlt1() != null
						&& castOther.getVelMinAlt1() != null && this
						.getVelMinAlt1().equals(castOther.getVelMinAlt1())))
				&& (this.getDirMinAlt1() == castOther.getDirMinAlt1())
				&& ((this.getTempMinAlt1() == castOther.getTempMinAlt1()) || (this
						.getTempMinAlt1() != null
						&& castOther.getTempMinAlt1() != null && this
						.getTempMinAlt1().equals(castOther.getTempMinAlt1())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDatosTodos();
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37
				* result
				+ (getVelPromAlt1() == null ? 0 : this.getVelPromAlt1()
						.hashCode());
		result = 37 * result + this.getDirPromAlt1();
		result = 37
				* result
				+ (getTempPromAlt1() == null ? 0 : this.getTempPromAlt1()
						.hashCode());
		result = 37
				* result
				+ (getDesvioAlt1() == null ? 0 : this.getDesvioAlt1()
						.hashCode());
		result = 37
				* result
				+ (getVelMaxAlt1() == null ? 0 : this.getVelMaxAlt1()
						.hashCode());
		result = 37 * result + this.getDirMaxAlt1();
		result = 37
				* result
				+ (getTempMaxAlt1() == null ? 0 : this.getTempMaxAlt1()
						.hashCode());
		result = 37
				* result
				+ (getVelMinAlt1() == null ? 0 : this.getVelMinAlt1()
						.hashCode());
		result = 37 * result + this.getDirMinAlt1();
		result = 37
				* result
				+ (getTempMinAlt1() == null ? 0 : this.getTempMinAlt1()
						.hashCode());
		return result;
	}

}
