package visual.client.basededatos;

// Generated 20/12/2012 19:47:27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewDatosAltura2Id generated by hbm2java
 */
@Embeddable
public class ViewDatosAltura2Id implements java.io.Serializable {

	private int idDatosTodos;
	private Date fecha;
	private Date hora;
	private BigDecimal velPromAlt2;
	private Integer dirPromAlt2;
	private BigDecimal tempPromAlt2;
	private BigDecimal desvioAlt2;
	private BigDecimal velMaxAlt2;
	private Integer dirMaxAlt2;
	private BigDecimal tempMaxAlt2;
	private BigDecimal velMinAlt2;
	private Integer dirMinAlt2;
	private BigDecimal tempMinAlt2;

	public ViewDatosAltura2Id() {
	}

	public ViewDatosAltura2Id(int idDatosTodos, Date fecha, Date hora) {
		this.idDatosTodos = idDatosTodos;
		this.fecha = fecha;
		this.hora = hora;
	}

	public ViewDatosAltura2Id(int idDatosTodos, Date fecha, Date hora,
			BigDecimal velPromAlt2, Integer dirPromAlt2,
			BigDecimal tempPromAlt2, BigDecimal desvioAlt2,
			BigDecimal velMaxAlt2, Integer dirMaxAlt2, BigDecimal tempMaxAlt2,
			BigDecimal velMinAlt2, Integer dirMinAlt2, BigDecimal tempMinAlt2) {
		this.idDatosTodos = idDatosTodos;
		this.fecha = fecha;
		this.hora = hora;
		this.velPromAlt2 = velPromAlt2;
		this.dirPromAlt2 = dirPromAlt2;
		this.tempPromAlt2 = tempPromAlt2;
		this.desvioAlt2 = desvioAlt2;
		this.velMaxAlt2 = velMaxAlt2;
		this.dirMaxAlt2 = dirMaxAlt2;
		this.tempMaxAlt2 = tempMaxAlt2;
		this.velMinAlt2 = velMinAlt2;
		this.dirMinAlt2 = dirMinAlt2;
		this.tempMinAlt2 = tempMinAlt2;
	}

	@Column(name = "idDatosTodos", nullable = false)
	public int getIdDatosTodos() {
		return this.idDatosTodos;
	}

	public void setIdDatosTodos(int idDatosTodos) {
		this.idDatosTodos = idDatosTodos;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "hora", nullable = false, length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "velPromAlt2", precision = 5)
	public BigDecimal getVelPromAlt2() {
		return this.velPromAlt2;
	}

	public void setVelPromAlt2(BigDecimal velPromAlt2) {
		this.velPromAlt2 = velPromAlt2;
	}

	@Column(name = "dirPromAlt2")
	public Integer getDirPromAlt2() {
		return this.dirPromAlt2;
	}

	public void setDirPromAlt2(Integer dirPromAlt2) {
		this.dirPromAlt2 = dirPromAlt2;
	}

	@Column(name = "tempPromAlt2", precision = 5)
	public BigDecimal getTempPromAlt2() {
		return this.tempPromAlt2;
	}

	public void setTempPromAlt2(BigDecimal tempPromAlt2) {
		this.tempPromAlt2 = tempPromAlt2;
	}

	@Column(name = "desvioAlt2", precision = 5)
	public BigDecimal getDesvioAlt2() {
		return this.desvioAlt2;
	}

	public void setDesvioAlt2(BigDecimal desvioAlt2) {
		this.desvioAlt2 = desvioAlt2;
	}

	@Column(name = "velMaxAlt2", precision = 5)
	public BigDecimal getVelMaxAlt2() {
		return this.velMaxAlt2;
	}

	public void setVelMaxAlt2(BigDecimal velMaxAlt2) {
		this.velMaxAlt2 = velMaxAlt2;
	}

	@Column(name = "dirMaxAlt2")
	public Integer getDirMaxAlt2() {
		return this.dirMaxAlt2;
	}

	public void setDirMaxAlt2(Integer dirMaxAlt2) {
		this.dirMaxAlt2 = dirMaxAlt2;
	}

	@Column(name = "tempMaxAlt2", precision = 5)
	public BigDecimal getTempMaxAlt2() {
		return this.tempMaxAlt2;
	}

	public void setTempMaxAlt2(BigDecimal tempMaxAlt2) {
		this.tempMaxAlt2 = tempMaxAlt2;
	}

	@Column(name = "velMinAlt2", precision = 5)
	public BigDecimal getVelMinAlt2() {
		return this.velMinAlt2;
	}

	public void setVelMinAlt2(BigDecimal velMinAlt2) {
		this.velMinAlt2 = velMinAlt2;
	}

	@Column(name = "dirMinAlt2")
	public Integer getDirMinAlt2() {
		return this.dirMinAlt2;
	}

	public void setDirMinAlt2(Integer dirMinAlt2) {
		this.dirMinAlt2 = dirMinAlt2;
	}

	@Column(name = "tempMinAlt2", precision = 5)
	public BigDecimal getTempMinAlt2() {
		return this.tempMinAlt2;
	}

	public void setTempMinAlt2(BigDecimal tempMinAlt2) {
		this.tempMinAlt2 = tempMinAlt2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewDatosAltura2Id))
			return false;
		ViewDatosAltura2Id castOther = (ViewDatosAltura2Id) other;

		return (this.getIdDatosTodos() == castOther.getIdDatosTodos())
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora()
						.equals(castOther.getHora())))
				&& ((this.getVelPromAlt2() == castOther.getVelPromAlt2()) || (this
						.getVelPromAlt2() != null
						&& castOther.getVelPromAlt2() != null && this
						.getVelPromAlt2().equals(castOther.getVelPromAlt2())))
				&& ((this.getDirPromAlt2() == castOther.getDirPromAlt2()) || (this
						.getDirPromAlt2() != null
						&& castOther.getDirPromAlt2() != null && this
						.getDirPromAlt2().equals(castOther.getDirPromAlt2())))
				&& ((this.getTempPromAlt2() == castOther.getTempPromAlt2()) || (this
						.getTempPromAlt2() != null
						&& castOther.getTempPromAlt2() != null && this
						.getTempPromAlt2().equals(castOther.getTempPromAlt2())))
				&& ((this.getDesvioAlt2() == castOther.getDesvioAlt2()) || (this
						.getDesvioAlt2() != null
						&& castOther.getDesvioAlt2() != null && this
						.getDesvioAlt2().equals(castOther.getDesvioAlt2())))
				&& ((this.getVelMaxAlt2() == castOther.getVelMaxAlt2()) || (this
						.getVelMaxAlt2() != null
						&& castOther.getVelMaxAlt2() != null && this
						.getVelMaxAlt2().equals(castOther.getVelMaxAlt2())))
				&& ((this.getDirMaxAlt2() == castOther.getDirMaxAlt2()) || (this
						.getDirMaxAlt2() != null
						&& castOther.getDirMaxAlt2() != null && this
						.getDirMaxAlt2().equals(castOther.getDirMaxAlt2())))
				&& ((this.getTempMaxAlt2() == castOther.getTempMaxAlt2()) || (this
						.getTempMaxAlt2() != null
						&& castOther.getTempMaxAlt2() != null && this
						.getTempMaxAlt2().equals(castOther.getTempMaxAlt2())))
				&& ((this.getVelMinAlt2() == castOther.getVelMinAlt2()) || (this
						.getVelMinAlt2() != null
						&& castOther.getVelMinAlt2() != null && this
						.getVelMinAlt2().equals(castOther.getVelMinAlt2())))
				&& ((this.getDirMinAlt2() == castOther.getDirMinAlt2()) || (this
						.getDirMinAlt2() != null
						&& castOther.getDirMinAlt2() != null && this
						.getDirMinAlt2().equals(castOther.getDirMinAlt2())))
				&& ((this.getTempMinAlt2() == castOther.getTempMinAlt2()) || (this
						.getTempMinAlt2() != null
						&& castOther.getTempMinAlt2() != null && this
						.getTempMinAlt2().equals(castOther.getTempMinAlt2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDatosTodos();
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37
				* result
				+ (getVelPromAlt2() == null ? 0 : this.getVelPromAlt2()
						.hashCode());
		result = 37
				* result
				+ (getDirPromAlt2() == null ? 0 : this.getDirPromAlt2()
						.hashCode());
		result = 37
				* result
				+ (getTempPromAlt2() == null ? 0 : this.getTempPromAlt2()
						.hashCode());
		result = 37
				* result
				+ (getDesvioAlt2() == null ? 0 : this.getDesvioAlt2()
						.hashCode());
		result = 37
				* result
				+ (getVelMaxAlt2() == null ? 0 : this.getVelMaxAlt2()
						.hashCode());
		result = 37
				* result
				+ (getDirMaxAlt2() == null ? 0 : this.getDirMaxAlt2()
						.hashCode());
		result = 37
				* result
				+ (getTempMaxAlt2() == null ? 0 : this.getTempMaxAlt2()
						.hashCode());
		result = 37
				* result
				+ (getVelMinAlt2() == null ? 0 : this.getVelMinAlt2()
						.hashCode());
		result = 37
				* result
				+ (getDirMinAlt2() == null ? 0 : this.getDirMinAlt2()
						.hashCode());
		result = 37
				* result
				+ (getTempMinAlt2() == null ? 0 : this.getTempMinAlt2()
						.hashCode());
		return result;
	}

}
